name: build-packages
on:
  push:
    # Prevents triggering multiple workflows in PRs. Workflows triggered from
    # the same commit shouldn't run simultaneously because they're overwriting
    # each other's packages on Anaconda.
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/tuttest.yml'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/workflows/tuttest.yml'
      - 'README.md'
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *' # run daily at 23:00 (UTC)
env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  ANACONDA_USER: ${{ secrets.ANACONDA_USER }}
  NUM_OF_JOBS: 69
defaults:
  run:
    shell: bash
jobs:

  #1
  magic-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "misc/magic"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #2
  icestorm-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "bit/icestorm"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #3
  prjtrellis-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "bit/prjtrellis"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #4
  prjoxide-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "bit/prjoxide"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #5
  prjxray-db-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "bit/prjxray-db"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #6
  prjxray-tools-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "bit/prjxray-tools"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #7
  icarus-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "sim/icarus"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #8
  verilator-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "sim/verilator"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #9
  yosys-linux-py37:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "syn/yosys"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.7"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #10
  yosys-linux-py38:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "syn/yosys"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.8"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #11
  yosys-plugins-symbiflow-linux:
    runs-on: "ubuntu-20.04"
    needs: ["icarus-linux", "yosys-linux-py37", "yosys-linux-py38"]
    env:
      PACKAGE: "syn/yosys-plugins-symbiflow"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #12
  nextpnr-nexus-linux:
    runs-on: "ubuntu-20.04"
    needs: ["prjoxide-linux"]
    env:
      PACKAGE: "pnr/nextpnr/nexus"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #13
  quicklogic-yosys-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "syn/quicklogic-yosys"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #14
  quicklogic-yosys-plugins-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "syn/quicklogic-yosys-plugins"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #15
  symbiflow-yosys-plugins-linux:
    runs-on: "ubuntu-20.04"
    needs: ["icarus-linux", "yosys-linux-py37"]
    env:
      PACKAGE: "syn/symbiflow-yosys-plugins"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #16
  vtr-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "pnr/vtr"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #17
  vtr-gui-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "pnr/vtr-gui"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #18
  vtr-optimized-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "pnr/vtr-optimized"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #19
  symbiflow-vtr-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "pnr/symbiflow-vtr"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #20
  symbiflow-vtr-gui-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "pnr/symbiflow-vtr-gui"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #21
  quicklogic-vtr-linux:
    runs-on: "ubuntu-20.04"
    needs: "vtr-linux"
    env:
      PACKAGE: "pnr/quicklogic-vtr"
      OS_NAME: "linux"
    steps:
      # Skip if token isn't available (cross-repository PRs mainly)
      - run: if [ "$ANACONDA_TOKEN" = "" ]; then echo "SKIP=true" >>$GITHUB_ENV; fi
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #22
  quicklogic-vtr-gui-linux:
    runs-on: "ubuntu-20.04"
    needs: "vtr-gui-linux"
    env:
      PACKAGE: "pnr/quicklogic-vtr-gui"
      OS_NAME: "linux"
    steps:
      # Skip if token isn't available (cross-repository PRs mainly)
      - run: if [ "$ANACONDA_TOKEN" = "" ]; then echo "SKIP=true" >>$GITHUB_ENV; fi
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #23
  nextpnr-ice40-linux:
    runs-on: "ubuntu-20.04"
    needs: ["icestorm-linux"]
    env:
      PACKAGE: "pnr/nextpnr/ice40"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #24
  nextpnr-ecp5-linux:
    runs-on: "ubuntu-20.04"
    needs: ["prjtrellis-linux"]
    env:
      PACKAGE: "pnr/nextpnr/ecp5"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #25
  nextpnr-generic-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "pnr/nextpnr/generic"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #26
  nextpnr-xilinx-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "pnr/nextpnr/xilinx"
      OS_NAME: "linux"
      KEEP_ALIVE: "true"
      USE_PYPY: "1"
    steps:
      - uses: actions/checkout@v2
      - name: 'Install pypy'
        run: |
          sudo add-apt-repository ppa:pypy/ppa -y
          sudo apt update
          sudo apt install -y pypy3
      - uses: hdl/conda-ci@master

  #27
  nextpnr-fpga_interchange-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "pnr/nextpnr/fpga_interchange"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #28
  symbiyosys-linux-py37:
    runs-on: "ubuntu-20.04"
    needs: "yosys-linux-py37"
    env:
      PACKAGE: "formal/symbiyosys"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.7"
      SKIP: "true"  # See https://github.com/litex-hub/litex-conda-eda/issues/70
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #29
  symbiyosys-linux-py38:
    runs-on: "ubuntu-20.04"
    needs: "yosys-linux-py38"
    env:
      PACKAGE: "formal/symbiyosys"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.8"
      SKIP: "true"  # See https://github.com/litex-hub/litex-conda-eda/issues/70
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #30
  xilinx-vivado-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "xilinx/vivado"
      OS_NAME: "linux"
      VERSIONS: ${{ format('{0}{1}', github.workspace, '/xilinx/vivado/versions') }} 
      SCRIPT: ${{ format('{0}{1}', github.workspace, '/xilinx/vivado/gen_metapackages.sh') }}
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #31
  icestorm-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "bit/icestorm"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #32
  prjtrellis-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "bit/prjtrellis"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #33
  icarus-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "sim/icarus"
      OS_NAME: "osx"
      SKIP: "true" # See https://github.com/hdl/conda-eda/issues/157
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #34
  verilator-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "sim/verilator"
      OS_NAME: "osx"
      SKIP: "true"  # See https://github.com/hdl/conda-eda/issues/97
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #35
  yosys-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "syn/yosys"
      OS_NAME: "osx"
      EXTRA_BUILD_ARGS: "--no-test"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #36
  quicklogic-yosys-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "syn/quicklogic-yosys"
      OS_NAME: "osx"
      EXTRA_BUILD_ARGS: "--no-test"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #37
  quicklogic-yosys-plugins-osx:
    runs-on: "macos-latest"
    needs: ["icarus-osx", "quicklogic-yosys-osx"]
    env:
      PACKAGE: "syn/quicklogic-yosys-plugins"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #38
  symbiflow-yosys-plugins-osx:
    runs-on: "macos-latest"
    needs: ["icarus-osx", "yosys-osx"]
    env:
      PACKAGE: "syn/symbiflow-yosys-plugins"
      OS_NAME: "osx"
      SKIP: "true"  # See https://github.com/litex-hub/litex-conda-eda/issues/71
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #39
  vtr-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "pnr/vtr"
      OS_NAME: "osx"
      SKIP: "true"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #40
  vtr-gui-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "pnr/vtr-gui"
      OS_NAME: "osx"
      SKIP: "true"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #41
  nextpnr-ice40-osx:
    runs-on: "macos-latest"
    needs: ["icestorm-osx"]
    env:
      PACKAGE: "pnr/nextpnr/ice40"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #42
  nextpnr-generic-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "pnr/nextpnr/generic"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #43
  icestorm-windows:
    runs-on: "windows-latest"
    env:
      PACKAGE: "bit/icestorm"
      OS_NAME: "windows"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #44
  prjtrellis-windows:
    runs-on: "windows-2016"
    env:
      PACKAGE: "bit/prjtrellis"
      OS_NAME: "windows"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #45
  icarus-windows:
    runs-on: "windows-latest"
    env:
      PACKAGE: "sim/icarus"
      OS_NAME: "windows"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #46
  yosys-windows:
    runs-on: "windows-latest"
    env:
      PACKAGE: "syn/yosys"
      OS_NAME: "windows"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #47
  quicklogic-yosys-windows:
    runs-on: "windows-latest"
    env:
      PACKAGE: "syn/quicklogic-yosys"
      OS_NAME: "windows"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #48
  nextpnr-ice40-windows:
    runs-on: "windows-2016"
    needs: ["icestorm-windows"] 
    env:
      PACKAGE: "pnr/nextpnr/ice40"
      OS_NAME: "windows"
      SKIP: "true"  # See: https://github.com/hdl/conda-eda/issues/120
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #49
  nextpnr-generic-windows:
    runs-on: "windows-2016"
    env:
      PACKAGE: "pnr/nextpnr/generic"
      OS_NAME: "windows"
      SKIP: "true"  # See: https://github.com/hdl/conda-eda/issues/120
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #50
  verible-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "sv-front/verible"
      USE_SYSTEM_GCC_VERSION: "9"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #51
  tree-sitter-verilog-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "misc/tree-sitter-verilog"
      OS_NAME: "linux"
      SKIP: "true"  # See https://github.com/litex-hub/litex-conda-eda/issues/73
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #52
  odin-ii-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "pnr/odin_II"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #53
  slang-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "sv-front/slang"
      OS_NAME: "linux"
      USE_SYSTEM_GCC_VERSION: "9"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #54
  sv-parser-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "sv-front/sv-parser"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #55
  moore-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "sv-front/moore"
      OS_NAME: "linux"
      SKIP: "true"  # See https://github.com/hdl/conda-eda/issues/163
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #56
  surelog-linux-py37:
    needs: ["libunwind", "gperftools"]
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "sv-front/surelog"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.7"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #57
  surelog-linux-py38:
    needs: ["libunwind", "gperftools"]
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "sv-front/surelog"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.8"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #58
  surelog-uhdm-linux-py37:
    needs: ["libunwind", "gperftools"]
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "sv-front/surelog-uhdm"
      USE_SYSTEM_GCC_VERSION: "9"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.7"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #59
  surelog-uhdm-linux-py38:
    needs: ["libunwind", "gperftools"]
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "sv-front/surelog-uhdm"
      USE_SYSTEM_GCC_VERSION: "9"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.8"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #60
  yosys-uhdm-linux-py37:
    needs: ["libunwind", "gperftools"]
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "syn/yosys-uhdm"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.7"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #61
  yosys-uhdm-linux-py38:
    needs: ["libunwind", "gperftools"]
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "syn/yosys-uhdm"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.8"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #62
  libunwind:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "misc/libunwind"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #63
  gperftools:
    needs: "libunwind"
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "misc/gperftools"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #64
  verilator-uhdm-linux-py37:
    needs: ["gperftools"]
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "sim/verilator-uhdm"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.7"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #65
  verilator-uhdm-linux-py38:
    needs: ["gperftools"]
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "sim/verilator-uhdm"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.8"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #66
  netgen-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "misc/netgen"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #67
  zachjs-sv2v-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "sv-front/zachjs-sv2v"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #68
  openroad-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "pnr/openroad"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #69
  open_pdks-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "misc/open_pdks"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  master-package:
    runs-on: "ubuntu-20.04"
    env:
      OS_NAME: "linux"
      CI_SCRIPTS_REL_PATH: "conda-ci"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: hdl/conda-ci
          ref: master
          path: ${{ env.CI_SCRIPTS_REL_PATH }}
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: urllib3
      - run: |
          # Required internally by the scripts to locate other scripts.
          export CI_SCRIPTS_PATH="$GITHUB_WORKSPACE/$CI_SCRIPTS_REL_PATH"
          bash $CI_SCRIPTS_PATH/install.sh
          python $CI_SCRIPTS_PATH/wait-for-statuses.py
