name: Build installers

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  openlane-linux:
    runs-on: "ubuntu-18.04"
    env:
      PACKAGE: "misc/openlane"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v3
      - name: 'Install tcllib'
        run: |
          sudo apt update
          sudo apt install -y tcllib
      - uses: ./ci
      - name: populate conda-bld cache
        uses: actions/cache@v3
        with:
          path: /home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld
          key: ${{ runner.os }}-openlane-${{ github.run_id }}

  constructor:
    needs:
      - openlane-linux
    runs-on: "ubuntu-18.04"
    steps:
      - name: restore openlane conda-bld cache
        uses: actions/cache@v3
        with:
          path: /home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld
          key: ${{ runner.os }}-openlane-${{ github.run_id }}
      - run: |
          ln -s /home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld /tmp/conda-bld
          source /home/runner/work/conda-eda/conda-eda/workdir/conda-env/
          conda install constructor
      - run: |
          constructor constructor/openlane.sky130a/
      - name: archive openlane.sky130a installer
        uses: actions/upload-artifact@v3
        with:
          name: "openlane.sky130a installer"
          path: openlane.sky130a-0-Linux-x86_64.sh
