name: Build installers

on:
  push:
    branch:
      - 'main'
  workflow_dispatch:

permissions:
  contents: write    

defaults:
  run:
    shell: bash

jobs:
  openlane-linux:
    outputs:
      OPENLANE_REV: ${{ steps.env.outputs.VOLARE_PATH }}
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "misc/openlane"
      OS_NAME: "linux"
    steps:
      - name: checkout conda-eda
        uses: actions/checkout@v3

      - name: 'Install tcllib'
        run: |
          sudo apt update
          sudo apt install -y tcllib

      - name: env
        id: env 
        run: |
          OPENLANE_REV=$(git ls-remote https://github.com/The-OpenROAD-Project/OpenLane.git HEAD | cut -f 1)
          echo "OPENLANE_REV=$OPENLANE_REV" >> $GITHUB_ENV
          echo "::set-output name=OPENLANE_REV::$OPENLANE_REV"
   
      - name: restore openlane cache
        id: cache-openlane
        uses: actions/cache@v3
        with:
          path: /home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld/linux-64/openlane-*.tar.bz2
          key: ${{ runner.os }}-openlane-${{ env.OPENLANE_REV }}         

      - uses: ./ci
        if: steps.cache-openlane.outputs.cache-hit != 'true'

  gf180mcuc-linux:
    outputs:
      GF180MCUC_REV: ${{ steps.env.outputs.GF180MCUC_REV }}
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "misc/open_pdks/gf180mcuc"
      OS_NAME: "linux"
    steps:
      - name: checkout conda-eda
        uses: actions/checkout@v3

      - name: env
        id: env
        run: |
          GF180MCUC_REV=$(grep volare misc/open_pdks/gf180mcuc/build.sh | cut -d / -f 8 | cut -d - -f 2)
          echo "GF180MCUC_REV=$GF180MCUC_REV" >> $GITHUB_ENV
          echo "::set-output name=GF180MCUC_REV::$GF180MCUC_REV"

      - name: restore gf180mcuc cache
        id: cache-gf180mcuc
        uses: actions/cache@v3
        with:
          path: /home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld/noarch/open_pdks.gf180mcuc-*.tar.bz2
          key: ${{ runner.os }}-gf180mcuc-${{ env.GF180MCUC_REV }}

      - uses: ./ci
        if: steps.cache-gf180mcuc.outputs.cache-hit != 'true'

  openlane-sky130a-installer:
    needs:
      - openlane-linux
    env:
      OPENLANE_REV: ${{ needs.openlane-linux.outputs.OPENLANE_REV }}
    runs-on: "ubuntu-20.04"
    steps:
      - uses: conda-incubator/setup-miniconda@v2

      - name: restore openlane cache
        uses: actions/cache@v3
        with:
          path: /home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld/linux-64/openlane-*.tar.bz2
          key: ${{ runner.os }}-openlane-${{ env.OPENLANE_REV }}         

      - name: construct installer
        run: |
          mkdir -p /tmp/conda-bld/{linux-64,noarch}
          cp /home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld/linux-64/openlane-*.tar.bz2 /tmp/conda-bld/linux-64/
          conda index /tmp/conda-bld
          conda install constructor
          constructor installer/openlane.sky130a/

      - name: archive installer
        uses: actions/upload-artifact@v3
        with:
          name: "openlane-sky130a-installer"
          path: |
            /home/runner/work/conda-eda/conda-eda/openlane-sky130a-0-Linux-x86_64.sh

  openlane-gf180mcuc-installer:
    needs:
      - openlane-linux
      - gf180mcuc-linux
    env:
      OPENLANE_REV: ${{ needs.openlane-linux.outputs.OPENLANE_REV }}
      GF180MCUC_REV: ${{ needs.gf180mcuc-linux.outputs.GF180MCUC_REV }}
    runs-on: "ubuntu-20.04"
    steps:
      - uses: conda-incubator/setup-miniconda@v2

      - name: restore openlane cache
        uses: actions/cache@v3
        with:
          path: /home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld/linux-64/openlane-*.tar.bz2
          key: ${{ runner.os }}-openlane-${{ env.OPENLANE_REV }}         

      - name: restore gf180mcuc cache
        uses: actions/cache@v3
        with:
          path: /home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld/noarch/open_pdks.gf180mcuc-*.tar.bz2
          key: ${{ runner.os }}-gf180mcuc-${{ env.GF180MCUC_REV }}

      - name: debug
        run: |
          find /home/runner/work/conda-eda/conda-eda/workdir/conda-env               

      - name: construct installer
        run: |
          mkdir -p /tmp/conda-bld/{linux-64,noarch}
          cp /home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld/linux-64/openlane-*.tar.bz2 /tmp/conda-bld/linux-64/
          cp /home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld/noarch/open_pdks.gf180mcuc-*.tar.bz2 /tmp/conda-bld/noarch/
          conda index /tmp/conda-bld
          conda install constructor
          constructor installer/openlane.gf180mcuc/

      - name: archive openlane.gf180mcuc installer
        uses: actions/upload-artifact@v3
        with:
          name: "openlane-gf180mcuc-installer"
          path: |
            /home/runner/work/conda-eda/conda-eda/openlane-gf180mcuc-0-Linux-x86_64.sh

  release:
    needs:
      - openlane-sky130a-installer
      - openlane-gf180mcuc-installer
    runs-on: "ubuntu-20.04"
    steps:
      - name: checkout conda-eda
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v3
        
      - run: |
          git config --local user.name conda-eda@bot
          git config --local user.email conda-eda@bot
          TAG=$(git describe --tags)
          git tag $TAG
          git push origin "HEAD:refs/tags/$TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.TAG }}
          tag_name: ${{ env.TAG }}
          files: |
            openlane-*-installer/*.sh
