name: Build installers

on:
  workflow_dispatch:

permissions:
  contents: write    

defaults:
  run:
    shell: bash

jobs:
  openlane-linux:
    runs-on: "ubuntu-18.04"
    env:
      PACKAGE: "misc/openlane"
      OS_NAME: "linux"
    steps:
      - name: checkout conda-eda
        uses: actions/checkout@v3

      - name: 'Install tcllib'
        run: |
          sudo apt update
          sudo apt install -y tcllib

      - uses: ./ci

      - name: populate conda-env cache
        uses: actions/cache@v3
        with:
          path: /home/runner/work/conda-eda/conda-eda/workdir/conda-env
          key: ${{ runner.os }}-openlane-${{ github.run_id }}          

  gf180mcuc-linux:
    runs-on: "ubuntu-18.04"
    env:
      PACKAGE: "misc/open_pdks/gf180mcuc"
      OS_NAME: "linux"
    steps:
      - name: checkout conda-eda
        uses: actions/checkout@v3

      - uses: ./ci

      - name: populate conda-env cache
        uses: actions/cache@v3
        with:
          path: /home/runner/work/conda-eda/conda-eda/workdir/conda-env
          key: ${{ runner.os }}-gf180mcuc-${{ github.run_id }}          


  openlane-sky130a-installer:
    needs:
      - openlane-linux
    runs-on: "ubuntu-18.04"
    steps:
      - name: checkout conda-eda
        uses: actions/checkout@v3

      - name: restore openlane conda-env cache
        uses: actions/cache@v3
        with:
          path: /home/runner/work/conda-eda/conda-eda/workdir/conda-env
          key: ${{ runner.os }}-openlane-${{ github.run_id }}

      - name: construct installer
        run: |
          ln -s /home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld /tmp/conda-bld
          /home/runner/work/conda-eda/conda-eda/workdir/conda-env/bin/conda install constructor
          /home/runner/work/conda-eda/conda-eda/workdir/conda-env/bin/constructor installer/openlane.sky130a/

      - name: archive openlane.sky130a installer
        uses: actions/upload-artifact@v3
        with:
          name: "openlane-sky130a-installer"
          path: |
            /home/runner/work/conda-eda/conda-eda/openlane-sky130a-0-Linux-x86_64.sh

  openlane-gf180mcuc-installer:
    needs:
      - openlane-linux
      - gf180mcuc-linux
    runs-on: "ubuntu-18.04"
    steps:
      - name: checkout conda-eda
        uses: actions/checkout@v3

      - name: restore openlane conda-env cache
        uses: actions/cache@v3
        with:
          path: /home/runner/work/conda-eda/conda-eda/workdir/conda-env
          key: ${{ runner.os }}-openlane-${{ github.run_id }}

      - name: construct installer
        run: |
          ln -s /home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld /tmp/conda-bld
          /home/runner/work/conda-eda/conda-eda/workdir/conda-env/bin/conda install constructor
          /home/runner/work/conda-eda/conda-eda/workdir/conda-env/bin/constructor installer/openlane.gf180mcuc/

      - name: archive openlane.gf180mcuc installer
        uses: actions/upload-artifact@v3
        with:
          name: "openlane-gf180mcuc-installer"
          path: |
            /home/runner/work/conda-eda/conda-eda/openlane-sky130a-0-Linux-x86_64.sh

  release:
    needs:
      - openlane-sky130a-installer
      - openlane-gf180mcuc-installer
    runs-on: "ubuntu-18.04"
    steps:
      - name: checkout conda-eda
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v3
        
      - run: |
          git config --local user.name conda-eda@bot
          git config --local user.email conda-eda@bot
          TAG=$(git describe --tags)
          git tag $TAG
          git push origin "HEAD:refs/tags/$TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.TAG }}
          tag_name: ${{ env.TAG }}
          files: |
            openlane-*-installer/*.sh
